{
 "title": "Cassandra.Compactions",
 "tags": [ "Cassandra" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "cassandra_Compaction_PendingTasks{}"
   },
   {
    "name": "instance",
    "query": "cassandra_Compaction_PendingTasks{app='$Cluster'}"
   },
   {
    "name": "groupBy",
    "query": "kubernetes_pod_name,service,keyspace"
   },
   {
    "name": "keyspace",
    "query": "cassandra_Keyspace_ReadLatency{app=\"$Cluster\"}"
   }
  ]
 },
 "panels": [
  { "title": "Compactions Per Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Compactions Completed / 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cassandra_Compaction_TotalCompactionsCompleted{app=~\"$Cluster\",kubernetes_pod_name=~\"[[instance]]\", function=\"Count\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Completed TP Compactions Tasks / 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(cassandra_Compaction_CompletedTasks{app=~\"$Cluster\",kubernetes_pod_name=~\"[[instance]]\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Compacted / 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(cassandra_Compaction_BytesCompacted{app=~\"$Cluster\",kubernetes_pod_name=~\"[[instance]]\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending TP Compaction Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_Compaction_PendingTasks{app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" }",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pending Compactions Per Keyspace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "[[keyspace]] TP Keyspace Pending Compactions / 5m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "repeat": "keyspace",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cassandra_Keyspace_PendingCompactions{app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\",keyspace=\"$keyspace\"}[5m])) by ($groupBy)",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  }
 ]
}