{
 "title": "Cassandra.CQLStatements",
 "tags": [ "Cassandra" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "cassandra_CQL_PreparedStatementsRatio{}"
   },
   {
    "name": "Instance",
    "query": "cassandra_CQL_PreparedStatementsRatio{app='$Cluster'}"
   },
   { "name": "GroupBy", "query": "kubernetes_pod_name,app" }
  ]
 },
 "panels": [
  { "title": "CQL Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prepared Statements Executed per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_CQL_PreparedStatementsExecuted{function=\"Count\",app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\"} [4m])) by ($GroupBy)",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "Regular Statements Executed per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum(irate(cassandra_CQL_RegularStatementsExecuted{function=\"Count\",app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\"} [4m])) by ($GroupBy)",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "Prepared Statements Ratio per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_CQL_PreparedStatementsRatio{function=\"Value\",app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Cached Prepared Statements per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_CQL_PreparedStatementsCount{function=\"Value\",app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prepared Statements Evicted per Second per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cassandra_CQL_PreparedStatementsEvicted{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\"}[4m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}