{
 "title": "Cassandra.ThreadPools",
 "tags": [ "Cassandra" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "cassandra_ThreadPools_ActiveTasks{}"
   },
   {
    "name": "instance",
    "query": "cassandra_ThreadPools_ActiveTasks{app=\"$Cluster\"}"
   },
   { "name": "groupBy", "query": "kubernetes_pod_name,app" },
   {
    "name": "poolName",
    "query": "MutationStage,ReadStage,RequestResponseStage,ReadRepairStage,CounterMutationStage,MiscStage,HintedHandoff,GossipStage,CacheCleanupExecutor,InternalResponseStage,CommitLogArchiver,CompactionExecutor,ValidationExecutor,MigrationStage,AntiEntropyStage,PendingRangeCalculator,Sampler,MemtableFlushWriter,MemtablePostFlush,,MemtableReclaimMemory,Native-Transport-Requests"
   }
  ]
 },
 "panels": [
  { "title": "$poolName Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "poolName" },
  {
   "title": "Active Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_ThreadPools_ActiveTasks{ThreadPools=\"$poolName\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" }) by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_ThreadPools_PendingTasks{ThreadPools=\"$poolName\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" }) by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "Completed Tasks Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_ThreadPools_CompletedTasks{ThreadPools=\"$poolName\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" }  [4m])) by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "Total Blocked Tasks Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_ThreadPools_TotalBlockedTasks{ThreadPools=\"$poolName\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m])) by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "Currently Blocked Tasks Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_ThreadPools_CurrentlyBlockedTasks{ThreadPools=\"$poolName\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m])) by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  }
 ]
}