{
 "title": "Cassandra.Data",
 "tags": [ "Cassandra" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "cassandra_Compaction_PendingTasks{}"
   },
   {
    "name": "Instance",
    "query": "cassandra_Compaction_PendingTasks{app='$Cluster'}"
   },
   {
    "name": "Keyspace",
    "query": "cassandra_Keyspace_ReadLatency{app=\"$Cluster\"}"
   },
   {
    "name": "ColumnFamily",
    "query": "cassandra_ColumnFamily_CompressionRatio{app=~\"$Cluster\",keyspace=~\"$Keyspace\"}"
   }
  ]
 },
 "panels": [
  { "title": "Compression", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Compression Ratio Per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_ColumnFamily_CompressionRatio{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\", ColumnFamily=~\"$ColumnFamily\", ColumnFamily!=\"\"} ",
     "legendFormat": "{{instance}}:{{keyspace}}:{{ColumnFamily}}"
    }
   ]
  },
  { "title": "Disk Space Per node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Live Disk Space Per ColumnFamily",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_ColumnFamily_LiveDiskSpaceUsed{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\", ColumnFamily=~\"$ColumnFamily\", ColumnFamily!=\"\"} ",
     "legendFormat": "{{instance}}:{{keyspace}}:{{ColumnFamily}}"
    },
    {
     "expr": "sum(cassandra_Keyspace_LiveDiskSpaceUsed{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\", keyspace=~\"$Keyspace\"}) by (instance) ",
     "legendFormat": "Total for {{instance}}"
    }
   ]
  },
  {
   "title": "Total Disk Space Per ColumnFamily",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_ColumnFamily_TotalDiskSpaceUsed{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\", keyspace=~\"$Keyspace\", ColumnFamily=~\"$ColumnFamily\", ColumnFamily!=\"\"}",
     "legendFormat": "{{instance}}-{{keyspace}}-{{ColumnFamily}}"
    },
    {
     "expr": "sum(cassandra_Keyspace_TotalDiskSpaceUsed{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\", keyspace=~\"$Keyspace\"}) by (instance)",
     "legendFormat": "Total for {{instance}}"
    }
   ]
  },
  { "title": "Row Size Per Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Min Row Size Per ColumnFamily",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_ColumnFamily_MinRowSize{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\", ColumnFamily=~\"$ColumnFamily\",ColumnFamily!=\"\"}",
     "legendFormat": "{{instance}}:{{keyspace}}:{{ColumnFamily}}"
    }
   ]
  },
  {
   "title": "Mean Row Size Per ColumnFamily",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_ColumnFamily_MeanRowSize{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\", ColumnFamily=~\"$ColumnFamily\",ColumnFamily!=\"\"}",
     "legendFormat": "{{instance}}:{{keyspace}}:{{ColumnFamily}}",
     "target": "avg(cassandra_ColumnFamily_MinRowSize{app=~\"$Cluster\",instance=~\"$instance\", ColumnFamily=~\"$ColumnFamily\"} ) by (instance).select metric"
    }
   ]
  },
  {
   "title": "Max Row Size Per ColumnFamily",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_ColumnFamily_MaxRowSize{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\", ColumnFamily=~\"$ColumnFamily\"}",
     "legendFormat": "{{instance}}:{{keyspace}}:{{ColumnFamily}}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Live SSTable Count Per ColumnFamily",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_ColumnFamily_LiveSSTableCount{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\", ColumnFamily=~\"$ColumnFamily\",ColumnFamily!=\"\"}",
     "legendFormat": "{{instance}}:{{keyspace}}:{{ColumnFamily}}"
    }
   ]
  },
  { "title": "Snapshot Size Per Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Snapshot Size Per ColumnFamily",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_ColumnFamily_SnapshotsSize{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\", ColumnFamily=~\"$ColumnFamily\",ColumnFamily!=\"\"}",
     "legendFormat": "{{instance}}:{{keyspace}}:{{ColumnFamily}}"
    }
   ]
  },
  {
   "title": "Total Snapshot Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_ColumnFamily_SnapshotsSize{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\",ColumnFamily=\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}