{
 "title": "Cassandra.Overview",
 "tags": [ "Cassandra" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "cassandra_Compaction_PendingTasks{}"
   },
   {
    "name": "instance",
    "query": "cassandra_Compaction_PendingTasks{app='$Cluster'}"
   },
   {
    "name": "groupBy",
    "query": "kubernetes_pod_name,app,keyspace"
   },
   {
    "name": "Percentile",
    "query": "cassandra_Keyspace_ReadLatency{app=\"$Cluster\"}"
   },
   {
    "name": "keyspace",
    "query": "cassandra_Keyspace_ReadLatency{app=\"$Cluster\"}"
   }
  ]
 },
 "panels": [
  { "title": "Availability Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Endpoints Down Per Node Point Of View",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "org_apache_cassandra_net_FailureDetector_DownEndpointCount{app=\"$Cluster\",kubernetes_pod_name=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Latency Statistics Per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coordinator Read Latency - $Percentile 'th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_ClientRequest_Latency{ClientRequest=\"Read\",Percentile=\"$Percentile\",app=\"$Cluster\",kubernetes_pod_name=~\"$instance\" }",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Coordinator Range Read Latency - $Percentile 'th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_ClientRequest_Latency{ClientRequest=\"RangeSlice\",Percentile=\"$Percentile\",app=\"$Cluster\",kubernetes_pod_name=~\"$instance\" }",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Coordinator Write Latency - $Percentile 'th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_ClientRequest_Latency{ClientRequest=\"Write\",Percentile=\"$Percentile\",app=\"$Cluster\",kubernetes_pod_name=~\"$instance\" }",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Read Latency Per Keyspace Per Node - $Percentile 'th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_Keyspace_ReadLatency{keyspace=~\"$keyspace\",Percentile=\"$Percentile\",function=\"Percentile\",app=\"$Cluster\",kubernetes_pod_name=~\"$instance\"} > 0",
       "legendFormat": "{{instance}}-{{keyspace}}",
       "target": "$graphFunction(rate(cassandra_ColumnFamily_ReadLatency{ColumnFamily=~\"$ColumnFamily\",keyspace=\"$keyspace\",function=\"$function\",app=\"$Cluster\",datacenter=\"$DC\",kubernetes_pod_name=~\"$instance\" }[2m])) by ($groupBy)"
      }
     ]
    },
    {
     "title": "Range Read Latency Per Keyspace Per Node - $Percentile 'th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_Keyspace_RangeLatency{keyspace=~\"$keyspace\",Percentile=\"$Percentile\",function=\"Percentile\",app=\"$Cluster\",kubernetes_pod_name=~\"$instance\"} > 0",
       "legendFormat": "{{instance}}-{{keyspace}}",
       "target": "$graphFunction(rate(cassandra_ColumnFamily_ReadLatency{ColumnFamily=~\"$ColumnFamily\",keyspace=\"$keyspace\",function=\"$function\",app=\"$Cluster\",datacenter=\"$DC\",kubernetes_pod_name=~\"$instance\" }[2m])) by ($groupBy)"
      }
     ]
    },
    {
     "title": "Write Latency Per Keyspace Per Node - $Percentile 'th Percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "cassandra_Keyspace_WriteLatency{keyspace=~\"$keyspace\",Percentile=\"$Percentile\",function=\"Percentile\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\"} > 0",
       "legendFormat": "{{instance}}-{{keyspace}}"
      }
     ]
    }
   ]
  },
  { "title": "Throughput Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Coordinator Read Request Count Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cassandra_ClientRequest_Latency{ClientRequest=\"Read\",function=\"Count\",app=\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m]))  by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "Coordinator Range Read Count Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cassandra_ClientRequest_Latency{ClientRequest=\"RangeSlice\",function=\"Count\",app=\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m]))  by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "Coordinator Write Request Count Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cassandra_ClientRequest_Latency{ClientRequest=\"Write\",function=\"Count\",app=\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m]))  by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "Reads Count Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_Keyspace_ReadLatency{keyspace=~\"$keyspace\",function=\"Count\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\"}[4m])) by ($groupBy)",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "Range Read Count Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_Keyspace_RangeLatency{keyspace=~\"$keyspace\",function=\"Count\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\"}[4m])) by ($groupBy)",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "Write Count Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_Keyspace_WriteLatency{keyspace=~\"$keyspace\",function=\"Count\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\"}[4m])) by ($groupBy)",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "Error Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coordinator Read Timeouts Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_ClientRequest_Timeouts{ClientRequest=\"CASRead\",app=\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m]))  by ($groupBy) ",
       "legendFormat": "{{$groupBy}}"
      }
     ]
    },
    {
     "title": "Coordinator Write Timeouts Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_ClientRequest_Timeouts{ClientRequest=\"CASWrite\",app=\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m]))  by ($groupBy) ",
       "legendFormat": "{{$groupBy}}"
      }
     ]
    },
    {
     "title": "Coordinator Read Unavailables Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_ClientRequest_Unavailables{ClientRequest=\"CASRead\",app=\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m]))  by ($groupBy) ",
       "legendFormat": "{{$groupBy}}"
      }
     ]
    },
    {
     "title": "Coordinator Write Unavailables Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cassandra_ClientRequest_Unavailables{ClientRequest=\"CASWrite\",app=\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m]))  by ($groupBy) ",
       "legendFormat": "{{$groupBy}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compactions Per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pending Compaction Tasks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_Compaction_PendingTasks{app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" }",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Completed Compaction Tasks / 5 min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(cassandra_Compaction_CompletedTasks{app=~\"$Cluster\",kubernetes_pod_name=~\"[[instance]]\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connected Clients Per Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Connected Thrift Clients",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_Client_connectedThriftClients{app=\"$Cluster\",kubernetes_pod_name=~\"$instance\" } ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Number Of Connections (Native)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "cassandra_Client_connectedNativeClients{app=\"$Cluster\",kubernetes_pod_name=~\"$instance\" } ",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}