{
 "title": "Cassandra.Entropy",
 "tags": [ "Cassandra" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "query": "cassandra_Storage_TotalHints{}" },
   {
    "name": "Instance",
    "query": "cassandra_Storage_TotalHints{app=~\"$Cluster\"}"
   },
   { "name": "GroupBy", "query": "kubernetes_pod_name,service" }
  ]
 },
 "panels": [
  { "title": "Hints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HintedHandOffManager Hints Created For Each IP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_HintedHandOffManager_Hints_created{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\" } [4m])) by (ip)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "TotalHints Created By Each Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(cassandra_Storage_TotalHints{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\" } [4m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TotalHintsInProgress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_Storage_TotalHintsInProgress{app=~\"$Cluster\",kubernetes_pod_name=~\"$Instance\" }",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Read RepairS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Attempted Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_ReadRepair_Attempted{app=~\"$Cluster\", function=\"Count\", kubernetes_pod_name=~\"$Instance\" } [4m])) by ($GroupBy)",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "RepairedBackground",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_ReadRepair_RepairedBackground{function=\"Count\",app=~\"$Cluster\"} [4m])) by ($GroupBy)",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "RepairedBlocking",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_ReadRepair_RepairedBlocking{function=\"Count\",app=~\"$Cluster\"} [4m])) by ($GroupBy)",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  { "title": "Coordinator Requests Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Write Timeouts Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cassandra_ClientRequest_Timeouts{ClientRequest=\"CASWrite\",app=\"$Cluster\",kubernetes_pod_name=~\"$Instance\" } [4m]))  by ($GroupBy) ",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "Write Unavailables Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cassandra_ClientRequest_Unavailables{ClientRequest=\"CASWrite\",app=\"$Cluster\",kubernetes_pod_name=~\"$Instance\"} [4m]))  by ($GroupBy) ",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  { "title": "Thread Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Completed Tasks Per 10 Minutes Window - Anti Entropy Stage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cassandra_ThreadPools_CompletedTasks{app=\"$Cluster\",kubernetes_pod_name=~\"$Instance\" ,ThreadPools=~\"AntiEntropyStage\"}[10m])) by ($GroupBy)",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "Completed Tasks Per 10 Minutes Window - Read Repair Stage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cassandra_ThreadPools_CompletedTasks{app=\"$Cluster\",kubernetes_pod_name=~\"$Instance\" ,ThreadPools=~\"ReadRepairStage\"}[10m])) by ($GroupBy)",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  },
  {
   "title": "Completed Tasks Per 10 Minutes Window - Hinted Handoff",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(cassandra_ThreadPools_CompletedTasks{app=\"$Cluster\",kubernetes_pod_name=~\"$Instance\",ThreadPools=~\"HintsDispatcher\"}[10m])) by ($GroupBy)",
     "legendFormat": "{{$GroupBy}}"
    }
   ]
  }
 ]
}