{
 "title": "Cassandra.Cache",
 "tags": [ "Cassandra" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": "cassandra_Compaction_PendingTasks{}"
   },
   { "name": "groupBy", "query": "kubernetes_pod_name,app" },
   {
    "name": "instance",
    "query": "cassandra_Compaction_PendingTasks{app='$Cluster'}\t"
   }
  ]
 },
 "panels": [
  { "title": "Key Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "KeyCache HitRate Per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cassandra_Cache_HitRate{Cache=\"KeyCache\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" } ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KeyCache Size vs Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_Cache_Size{Cache=\"KeyCache\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" })  by ($groupBy) ",
     "legendFormat": "size_{{$groupBy}}"
    },
    {
     "expr": "sum(cassandra_Cache_Capacity{Cache=\"KeyCache\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" } )  by ($groupBy) ",
     "legendFormat": "capacity_{{$groupBy}}"
    }
   ]
  },
  {
   "title": "KeyCache Number of Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_Cache_Entries{Cache=\"KeyCache\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" })  by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "KeyCache Requests Count Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_Cache_Requests{Cache=\"KeyCache\",function=\"Count\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m]))  by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  { "title": "Row Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "RowCache HitRate Per Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cassandra_Cache_HitRate{Cache=\"RowCache\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" } ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RowCache Size vs Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_Cache_Size{Cache=\"RowCache\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" })  by ($groupBy) ",
     "legendFormat": "size_{{$groupBy}}"
    },
    {
     "expr": "sum(cassandra_Cache_Capacity{Cache=\"RowCache\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" } )  by ($groupBy) ",
     "legendFormat": "capacity_{{$groupBy}}"
    }
   ]
  },
  {
   "title": "RowCache Number of Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_Cache_Entries{Cache=\"RowCache\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" })  by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "RowCache Requests Count Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_Cache_Requests{Cache=\"RowCache\",function=\"Count\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m]))  by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  { "title": "Counter Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "CounterCache HitRate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cassandra_Cache_HitRate{Cache=\"CounterCache\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" }",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CounterCache Size vs Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_Cache_Size{Cache=\"CounterCache\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" })  by ($groupBy) ",
     "legendFormat": "size_{{$groupBy}}"
    },
    {
     "expr": "sum(cassandra_Cache_Capacity{Cache=\"CounterCache\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" } )  by ($groupBy) ",
     "legendFormat": "capacity_{{$groupBy}}"
    }
   ]
  },
  {
   "title": "CounterCache Number of Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_Cache_Entries{Cache=\"CounterCache\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" })  by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "CounterCache Requests Count Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cassandra_Cache_Requests{Cache=\"CounterCache\",function=\"Count\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m]))  by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  { "title": "File Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "FileCache HitRate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cassandra_FileCache_HitRate{app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" }",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FileCache Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(cassandra_FileCache_Size{servicename=\"$Cluster\",kubernetes_pod_name=~\"$instance\" } )  by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  },
  {
   "title": "FileCache Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cassandra_FileCache_Requests{function=\"Count\",app=~\"$Cluster\",kubernetes_pod_name=~\"$instance\" } [4m]))  by ($groupBy) ",
     "legendFormat": "{{$groupBy}}"
    }
   ]
  }
 ]
}